
allstocks = ['HDFCBANK','RELIANCE','INFY','ICICIBANK','TCS','KOTAKBANK','ITC','LT','HINDUNILVR','AXISBANK','SBIN','BAJFINANCE','BHARTIARTL','ASIANPAINT','HCLTECH','TITAN','TATASTEEL','MARUTI','SUNPHARMA','BAJAJFINSV','M&M','TECHM','POWERGRID','ULTRACEMCO','WIPRO','HINDALCO','JSWSTEEL','NESTLEIND','GRASIM','INDUSINDBK','ADANIPORTS','ONGC','DIVISLAB','HDFCLIFE','CIPLA','DRREDDY','TATACONSUM','SBILIFE','APOLLOHOSP','BAJAJ-AUTO','UPL','COALINDIA','EICHERMOT','BPCL','SHREECEM','HEROMOTOCO',
            'BDL', 'ADANIPOWER', 'LUPIN', 'FLUOROCHEM', 'TORNTPOWER', 'LALPATHLAB', 'GLAND', 'MAZDOCK', 'BHARATFORG', 'DALBHARAT', 'IPCALAB', 'KPITTECH', 'POLICYBZR', 'JSWENERGY', 'SYNGENE', 'JUBLFOOD', 'ZEEL', 'LODHA', 'TIINDIA', 'LAURUSLABS', 'NMDC', 'ALKEM', 'SUNTV', 'DEVYANI', 'POLYCAB', 'UNIONBANK', 'ABFRL', 'LTTS', 'NAVINFLUOR', 'BALKRISIND', 'APLAPOLLO', 'IGL', 'AUBANK', 'BIOCON', 'TATACOMM', 'AUROPHARMA', 'ACC', 'RVNL', 'ASHOKLEY', 'DELHIVERY', 'BATAINDIA', 'COROMANDEL', 'FEDERALBNK', 'OIL', 'FORTIS', 'MRF', 'IDFCFIRSTB', 'BANDHANBNK', 'LICHSGFIN', 'HDFCAMC', 'ESCORTS', 'INDHOTEL', 'PRESTIGE', 'COFORGE', 'PERSISTENT', 'MFSL', 'INDUSTOWER', 'MSUMI', 'PFC', 'PAGEIND', 'CUMMINSIND', 'PETRONET', 'MAXHEALTH', 'DEEPAKNTR', 'NYKAA', 'FACT', 'IRFC', 'RAMCOCEM', 'CONCOR', 'TATAELXSI', 'GODREJPROP', 'SAIL', 'GUJGASLTD', 'TATACHEM', 'NHPC', 'INDIANB', 'OBEROIRLTY', 'BANKINDIA', 'RECLTD', 'ASTRAL', 'SONACOMS', 'APOLLOTYRE', 'MANKIND', 'DIXON', 'VOLTAS', 'UBL', 'POONAWALLA', 'LTF',  'CROMPTON', 'ABCAPITAL', 'YESBANK', 'HINDPETRO', 'PATANJALI', 'IDEA', 'MPHASIS', 'M&MFIN', 'PAYTM', 'CGPOWER',
            'DATAPATTNS', 'AEGISLOG', 'GRANULES', 'MRPL', 'SUZLON', 'IRB', 'ANGELONE', 'BSE', 'REDINGTON', 'LATENTVIEW', 'INTELLECT', 'METROPOLIS', 'BIKAJI', 'CYIENT', 'ARE&M', 'CREDITACC', 'GLENMARK', 'JYOTHYLAB', 'HINDCOPPER', 'COCHINSHIP', 'SJVN', 'CDSL', 'UTIAMC', 'ANURAS', 'EASEMYTRIP', 'AFFLE', 'BIRLACORPN', 'KARURVYSYA', 'FINCABLES', 'TTML', 'CEATLTD', 'INDIAMART', 'JBMA', 'MEDANTA', 'NATIONALUM', 'KALYANKJIL', 'FSL', 'IDBI', 'BALAMINES', 'KEI', 'AMBER', 'TANLA', 'IOB', 'ZENSARTECH', 'PVRINOX', 'MCX', 'AAVAS', 'NSLNISP', 'HFCL', 'CUB', 'HAPPSTMNDS', 'SONATSOFTW', 'MEDPLUS']

new=['CAMS', 'JUBLINGREA', 'UCOBANK', 'IIFL', 'JKLAKSHMI', 'MGL', 'CIEINDIA', 'CHAMBLFERT', 'DEEPAKFERT', 'RITES', 'EQUITASBNK', 'EXIDEIND', 'PPLPHARMA', 'CENTRALBK', 'BLS', 'TRITURBINE', 'ELGIEQUIP', 'HUDCO', 'NATCOPHARM', 'PRAJIND', 'KEC', 'TEJASNET', 'RADICO', 'ROUTE', 'CESC', 'LXCHEM', 'NLCINDIA', 'APARINDS',   'NBCC', 'GRAPHITE', 'JBCHEPHARM', 'RBLBANK', 'RAYMOND', 'PNBHOUSING', 'VIPIND', 'CAMPUS', 'CANFINHOME', 'MANAPPURAM', 'GNFC', 'IEX', 'BALRAMCHIN', 'RENUKA'
             ]
Index = ['NIFTY 50', 'NIFTY50 EQL WGT', 'NIFTY100 EQL WGT', 'NIFTY100 LOWVOL30', 'NIFTY ALPHA 50', 'NIFTY MIDCAP 150', 'NIFTY SMLCAP 50', 'NIFTY SMLCAP 250', 'NIFTY MIDSML 400', 'NIFTY200 QUALTY30', 'NIFTY FINSRV25 50', 'NIFTY ALPHALOWVOL', 'NIFTY200MOMENTM30', 'NIFTY100ESGSECLDR', 'NIFTY100 ESG', 'NIFTY M150 QLTY50', 'NIFTY INDIA MFG', 'NIFTY IT', 'NIFTY NEXT 50', 'NIFTY BANK', 'NIFTY MIDCAP 100', 'NIFTY 500', 'NIFTY 100', 'NIFTY MIDCAP 50', 'NIFTY REALTY', 'NIFTY INFRA', 'NIFTY ENERGY', 'NIFTY FMCG', 'NIFTY MNC', 'NIFTY PHARMA', 'NIFTY PSE', 'NIFTY PSU BANK', 'NIFTY SERV SECTOR', 'INDIA VIX', 'NIFTY AUTO', 'NIFTY METAL', 'NIFTY MEDIA', 'NIFTY SMLCAP 100', 'NIFTY 200', 'NIFTY DIV OPPS 50', 'NIFTY COMMODITIES', 'NIFTY CONSUMPTION', 'NIFTY FIN SERVICE', 'NIFTY50 DIV POINT', 'NIFTY100 LIQ 15', 'NIFTY CPSE', 'NIFTY GROWSECT 15', 'NIFTY50 PR 2X LEV', 'NIFTY50 PR 1X INV', 'NIFTY50 TR 2X LEV', 'NIFTY50 TR 1X INV', 'NIFTY50 VALUE 20', 'NIFTY MID LIQ 15', 'NIFTY PVT BANK', 'NIFTY100 QUALTY30', 'NIFTY GS 8 13YR', 'NIFTY GS 10YR', 'NIFTY GS 10YR CLN', 'NIFTY GS 4 8YR', 'NIFTY GS 11 15YR', 'NIFTY GS 15YRPLUS', 'NIFTY GS COMPSITE', 'NIFTY HEALTHCARE', 'NIFTY CONSR DURBL', 'NIFTY OIL AND GAS', 'NIFTY500 MULTICAP', 'NIFTY LARGEMID250', 'NIFTY MID SELECT', 'NIFTY TOTAL MKT', 'NIFTY MICROCAP250', 'NIFTY IND DIGITAL']
indexTest = ['Nifty 50','NIFTY50 EQL WGT', 'NIFTY100 EQL WGT', 'NIFTY100 LOWVOL30', 'NIFTY ALPHA 50']

commodities = ['ALUMINIUM FUT 29 NOV 24','COPPER FUT 29 NOV 24','LEAD FUT 29 NOV 24','NICKEL FUT 29 NOV 24','ZINC FUT 29 NOV 24',
               'KAPAS FUT 29 NOV 24','COTTONCNDY FUT 29 NOV 24','MENTHAOIL FUT 29 NOV 24','SILVERM FUT 29 NOV 24',
               'STEELREBAR FUT 29 NOV 24']
NiftyMidcap100 = ['BDL', 'ADANIPOWER', 'LUPIN', 'FLUOROCHEM', 'TORNTPOWER', 'LALPATHLAB', 'GLAND', 'MAZDOCK', 'BHARATFORG', 'DALBHARAT', 'IPCALAB', 'KPITTECH', 'POLICYBZR', 'JSWENERGY', 'SYNGENE', 'JUBLFOOD', 'ZEEL', 'LODHA', 'TIINDIA', 'LAURUSLABS', 'NMDC', 'ALKEM', 'SUNTV', 'DEVYANI', 'POLYCAB', 'UNIONBANK', 'ABFRL', 'LTTS', 'NAVINFLUOR', 'BALKRISIND', 'APLAPOLLO', 'IGL', 'AUBANK', 'BIOCON', 'TATACOMM', 'AUROPHARMA', 'ACC', 'RVNL', 'ASHOKLEY', 'DELHIVERY', 'BATAINDIA', 'COROMANDEL', 'FEDERALBNK', 'OIL', 'FORTIS', 'MRF', 'IDFCFIRSTB', 'BANDHANBNK', 'LICHSGFIN', 'HDFCAMC', 'ESCORTS', 'INDHOTEL', 'PRESTIGE', 'COFORGE', 'PERSISTENT', 'MFSL', 'INDUSTOWER', 'MSUMI', 'PFC', 'PAGEIND', 'CUMMINSIND', 'PETRONET', 'MAXHEALTH', 'DEEPAKNTR', 'NYKAA', 'FACT', 'IRFC', 'RAMCOCEM', 'CONCOR', 'TATAELXSI', 'GODREJPROP', 'SAIL', 'GUJGASLTD', 'TATACHEM', 'NHPC', 'INDIANB', 'OBEROIRLTY', 'BANKINDIA', 'RECLTD', 'ASTRAL', 'SONACOMS', 'APOLLOTYRE', 'MANKIND', 'DIXON', 'VOLTAS', 'UBL', 'POONAWALLA', 'LTF',  'CROMPTON', 'ABCAPITAL', 'YESBANK', 'HINDPETRO', 'PATANJALI', 'IDEA', 'MPHASIS', 'M&MFIN', 'PAYTM', 'CGPOWER']

fno_stocks = ['AARTIIND','ABB','ABBOTINDIA','ABCAPITAL','ABFRL','ACC','ADANIENT','ADANIPORTS','ALKEM','AMBUJACEM','APOLLOHOSP','APOLLOTYRE','ASHOKLEY','ASIANPAINT','ASTRAL','ATUL','AUBANK','AUROPHARMA','AXISBANK','BAJAJ-AUTO','BAJAJFINSV','BAJFINANCE','BALKRISIND','BALRAMCHIN','BANDHANBNK','BANKBARODA','BATAINDIA','BEL','BERGEPAINT','BHARATFORG','BHARTIARTL','BHEL','BIOCON','BOSCHLTD','BPCL','BRITANNIA','CANBK','CANFINHOME','CHAMBLFERT','CHOLAFIN','CIPLA','COALINDIA','COFORGE','COLPAL','CONCOR','COROMANDEL','CROMPTON','CUB','CUMMINSIND','DABUR','DALBHARAT','DEEPAKNTR','DIVISLAB','DIXON','DLF','DRREDDY','EICHERMOT','ESCORTS','EXIDEIND','FEDERALBNK','GAIL','GLENMARK','GNFC','GODREJCP','GODREJPROP','GRANULES','GRASIM','GUJGASLTD','HAL','HAVELLS','HCLTECH','HDFCAMC','HDFCBANK','HDFCLIFE','HEROMOTOCO','HINDALCO','HINDCOPPER','HINDPETRO','HINDUNILVR','ICICIBANK','ICICIGI',
              'ICICIPRULI','IDEA','IDFCFIRSTB','IEX','IGL','INDHOTEL','INDIACEM','INDIAMART','INDIGO','INDUSINDBK','INDUSTOWER','INFY','IOC','IPCALAB','IRCTC','ITC','JINDALSTEL','JKCEMENT','JSWSTEEL','JUBLFOOD','KOTAKBANK','LALPATHLAB','LAURUSLABS','LICHSGFIN','LT','LTF','LTIM','LTTS','LUPIN','M&M','M&MFIN','MANAPPURAM','MARICO','MARUTI','MCX','METROPOLIS','MFSL','MGL','MOTHERSON','MPHASIS','MRF','MUTHOOTFIN','NATIONALUM','NAUKRI','NAVINFLUOR','NESTLEIND','NIFTY','NMDC','NTPC','OBEROIRLTY','OFSS','ONGC','PAGEIND','PERSISTENT','PETRONET','PFC','PIDILITIND','PIIND','PNB','POLYCAB','POWERGRID','PVRINOX','RAMCOCEM','RBLBANK','RECLTD','RELIANCE','SAIL','SBICARD','SBILIFE','SBIN','SHREECEM','SHRIRAMFIN','SIEMENS','SRF','SUNPHARMA','SUNTV','SYNGENE','TATACHEM','TATACOMM','TATACONSUM','TATAPOWER','TATASTEEL','TCS','TECHM','TITAN','TORNTPHARM','TRENT','TVSMOTOR','UBL','ULTRACEMCO','UNITDSPR','UPL','VEDL','VOLTAS','WIPRO','ZYDUSLIFE' ]
sample=['IREDA','HDFCBANK','GLAND','KRBL','DEEPAKNTR','IDBI','KALYANKJIL','NSLNISP','ZEEL']
hdfc=['CROMPTON']

SectorIndex = ['NIFTY FINSRV25 50','NIFTY INDIA MFG', 'NIFTY IT', 'NIFTY BANK', 'NIFTY REALTY', 'NIFTY INFRA', 'NIFTY ENERGY', 'NIFTY FMCG', 'NIFTY MNC', 'NIFTY PHARMA', 'NIFTY PSE', 'NIFTY PSU BANK', 'NIFTY SERV SECTOR', 'NIFTY AUTO', 'NIFTY HEALTHCARE', 'NIFTY CONSR DURBL', 'NIFTY OIL AND GAS','NIFTY METAL', 'NIFTY MEDIA', 'NIFTY COMMODITIES', 'NIFTY CONSUMPTION', 'NIFTY FIN SERVICE']
IndiaVix =[ 'INDIA VIX']

mystocks = ['IREDA','INFY','ACC','HDFCBANK']

microcap= [ 'AGI','ASKAUTOLTD','AARTIDRUGS','AARTIPHARM','ACCELYA','ADVENZYMES','AHLUCONT','AMIORG','ANANTRAJ','ARVINDFASN','ARVIND','ASHOKA','ASTRAMICRO','AVALON','AZAD','BASF','BAJAJCON','BAJAJHIND','BALMLAWRIE','BANCOINDIA','BARBEQUE','BEPL','BLUEJET','BOMDYEING','CARERATING','CMSINFO','CAMLINFINE','CARTRADE','CHOICEIN','CIGNITITEC','CONFIPET','CYIENTDLM','DBCORP','DCBBANK','DCXINDIA','DALMIASUG','DATAMATICS','DELTACORP','DEN','DHANI','DHANUKA','DBL','DISHTV','DCAL','DODLA','DREAMFOLKS','DUMMYINFBM','ESAFSFB','EDELWEISS','EMIL','ELECTCAST','EPIGRAL','EMBDL','ETHOSLTD','EVEREADY','FEDFINA','FIEMIND','FCL','FLAIR','FUSION','GRINFRA','GHCL','GABRIEL','GALAXYSURF','GANESHHOUC','GRWRHITECH','GATEWAY','GLOBUSSPR','GOCOLORS','GODREJAGRO','GOKEX','GRAVITA','GREAVESCOT','GREENPANEL','GREENPLY','GUFICBIO','GUJALKALI','GULFOILLUB','HGINFRA','HLEGLAS','HMAAGRO','HATHWAY','HEIDELBERG','HEMIPROP',
            'HERITGFOOD','HIKAL','HCC','HINDOILEXP','HINDWAREAP','IFBIND','IFCI','IIFLSEC','IKIO','INOXINDIA','IOLCP','ITDCEM','IDEAFORGE','INDIAGLYCO','IPL','INDIASHLTR','IMFA','ICIL','INDOCO','INFIBEAM','INGERRAND','IONEXCHANG','ISGEC','JKIL','JKTYRE','JSWHL','JTEKTINDIA','JTLIND','JAICORPLTD','JISLJALEQS','JPASSOCIAT','JPPOWER','JAMNAAUTO','JINDWORLD','JCHAC','JUNIPER','JLHL','JYOTICNC','KPIGREEN','KSL','KTKBANK','KSCL','KESORAMIND','KIRLOSBROS','KIRLOSENG','KOLTEPATIL','KRSNAA','LGBBROSLTD','LTFOODS','LAOPALA','LANDMARK','LLOYDSENGG','LUXIND','MASFIN','MOIL','MSTCLTD','MAHLOG','MAITHANALL','MANINFRA','MARKSANS','MIDHANI','BECTORFOOD','MUTHOOTMF','NESCO','NIITMTS','NOCIL','NRBBEARING','NFL','NAVA','NAVNETEDUL','NAZARA','NETWEB','NEULANDLAB','NEWGEN','NUCLEUS','OPTIEMUS','ORIENTCEM','ORIENTELEC','ORISSAMINE','PDSL','PGEL','PSPPROJECT','PTC','PAISALO','PARADEEP','PARAS','PATELENG',
            'POLYPLEX','POWERMECH','PRICOLLTD','PURVA','RAIN','RALLIS','RAMKY','RATEGAIN','RTNPOWER','REDTAPE','RELINFRA','RPOWER','RELIGARE','RESPONIND','ROSSARI','SAGCEM','KALAMANDIR','SAMHI','SANDUMA','SANGHIIND','SANGHVIMOV','SANSERA','SARDAEN','SENCO','SEQUENT','SHARDAMOTR','SHAREINDIA','SFL','SHILPAMED','SCI','SBCL','SHOPERSTOP','SINDHUTRAD','SOUTHBANK','SPANDANA','STARCEMENT','SSWL','STAR','STYLAMIND','SUDARSCHEM','SULA','SUNCLAY','SUNFLAG','SUPRAJIT','SPLPETRO','SUPRIYA','SURYAROSNI','TARC','TDPOWERSYS','TTKPRESTIG','TVSHLTD','TARSONS','TEAMLEASE','TECHNOE','TEGA','TEXRAIL','TIRUMALCHM','THOMASCOOK','TIDEWATER','TI','TIMETECHNO','TIPSINDLTD','UFLEX','UNIPARTS','UTKARSHBNK','VMART','VSTTILLERS','VRLLOG','WABAG','DBREALTY','VENKEYS','VOLTAMP','WELENT','WSTCSTPAPR','WOCKPHARMA','WONDERLA','YATHARTH','ZENTEC','ZYDUSWELL']

nifty500 = ['360ONE', '3MINDIA', 'ABB', 'ACC', 'AIAENG', 'APLAPOLLO', 'AUBANK', 'AARTIIND', 'AAVAS', 'ABBOTINDIA', 'ACE', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'ATGL', 'AWL', 'ABCAPITAL', 'ABFRL', 'AEGISLOG', 'AETHER', 'AFFLE', 'AJANTPHARM', 'APLLTD', 'ALKEM', 'ALKYLAMINE', 'ALLCARGO', 'ALOKINDS', 'ARE&M', 'AMBER', 'AMBUJACEM', 'ANANDRATHI', 'ANGELONE', 'ANURAS', 'APARINDS', 'APOLLOHOSP', 'APOLLOTYRE', 'APTUS', 'ACI', 'ASAHIINDIA', 'ASHOKLEY', 'ASIANPAINT', 'ASTERDM', 'ASTRAZEN', 'ASTRAL', 'ATUL', 'AUROPHARMA', 'AVANTIFEED', 'DMART', 'AXISBANK', 'BEML', 'BLS', 'BSE', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV', 'BAJAJHLDNG', 'BALAMINES', 'BALKRISIND', 'BALRAMCHIN', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'MAHABANK', 'BATAINDIA', 'BAYERCROP', 'BERGEPAINT', 'BDL', 'BEL', 'BHARATFORG', 'BHEL', 'BPCL', 'BHARTIARTL', 'BIKAJI', 'BIOCON', 'BIRLACORPN', 
            'BLUEDART', 'BLUESTARCO', 'BBTC', 'BORORENEW', 'BOSCHLTD', 'BRIGADE', 'BRITANNIA', 'MAPMYINDIA', 'CCL', 'CESC', 'CGPOWER', 'CIEINDIA', 'CRISIL', 'CSBBANK', 'CAMPUS', 'CANFINHOME', 'CANBK', 'CAPLIPOINT', 'CGCL', 'CARBORUNIV', 'CASTROLIND', 'CEATLTD', 'CELLO', 'CENTRALBK', 'CDSL', 'CENTURYPLY',  'CERA', 'CHALET', 'CHAMBLFERT', 'CHEMPLASTS', 'CHENNPETRO', 'CHOLAHLDNG', 'CHOLAFIN', 'CIPLA', 'CUB', 'CLEAN', 'COALINDIA', 'COCHINSHIP', 'COFORGE', 'COLPAL', 'CAMS', 'CONCORDBIO', 'CONCOR', 'COROMANDEL', 'CRAFTSMAN', 'CREDITACC', 'CROMPTON', 'CUMMINSIND', 'CYIENT', 'DCMSHRIRAM', 'DLF', 'DOMS', 'DABUR', 'DALBHARAT', 'DATAPATTNS', 'DEEPAKFERT', 'DEEPAKNTR', 'DELHIVERY', 'DEVYANI', 'DIVISLAB', 'DIXON', 'LALPATHLAB', 'DRREDDY', 'EIDPARRY', 'EIHOTEL', 'EPL', 'EASEMYTRIP', 'EICHERMOT', 'ELECON', 'ELGIEQUIP', 'EMAMILTD', 'ENDURANCE', 'ENGINERSIN', 'EQUITASBNK', 'ERIS', 'ESCORTS',
            'EXIDEIND', 'FDC', 'NYKAA', 'FEDERALBNK', 'FACT', 'FINEORG', 'FINCABLES', 'FINPIPE', 'FSL', 'FIVESTAR', 'FORTIS', 'GAIL', 'GMMPFAUDLR',  'GRSE', 'GICRE', 'GILLETTE', 'GLAND', 'GLAXO',  'GLENMARK', 'MEDANTA', 'GPIL', 'GODFRYPHLP', 'GODREJCP', 'GODREJIND', 'GODREJPROP', 'GRANULES', 'GRAPHITE', 'GRASIM', 'GESHIP', 'GRINDWELL', 'GAEL', 'FLUOROCHEM', 'GUJGASLTD', 'GMDCLTD', 'GNFC', 'GPPL', 'GSFC', 'GSPL', 'HEG',  'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HFCL', 'HAPPSTMNDS', 'HAPPYFORGE', 'HAVELLS', 'HEROMOTOCO', 'HSCL', 'HINDALCO', 'HAL', 'HINDCOPPER', 'HINDPETRO', 'HINDUNILVR', 'HINDZINC', 'POWERINDIA', 'HOMEFIRST', 'HONASA', 'HONAUT', 'HUDCO', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI',  'IDBI', 'IDFCFIRSTB',  'IIFL', 'IRB', 'IRCON', 'ITC', 'ITI', 'INDIACEM', 'INDIAMART', 'INDIANB', 'IEX', 'INDHOTEL', 'IOC', 'IOB', 'IRCTC', 'IRFC',
            'INDIGOPNTS', 'IGL', 'INDUSTOWER', 'INDUSINDBK', 'NAUKRI', 'INFY', 'INOXWIND', 'INTELLECT', 'INDIGO', 'IPCALAB', 'JBCHEPHARM', 'JKCEMENT', 'JBMA', 'JKLAKSHMI', 'JKPAPER', 'JMFINANCIL', 'JSWENERGY', 'JSWINFRA', 'JSWSTEEL', 'JAIBALAJI', 'J&KBANK', 'JINDALSAW', 'JSL', 'JINDALSTEL', 'JIOFIN', 'JUBLFOOD', 'JUBLINGREA', 'JUBLPHARMA', 'JWL', 'JUSTDIAL', 'JYOTHYLAB', 'KPRMILL', 'KEI', 'KNRCON', 'KPITTECH', 'KRBL', 'KSB', 'KAJARIACER', 'KPIL', 'KALYANKJIL', 'KANSAINER', 'KARURVYSYA', 'KAYNES', 'KEC', 'KFINTECH', 'KOTAKBANK', 'KIMS', 'LTF', 'LTTS', 'LICHSGFIN', 'LTIM', 'LT', 'LATENTVIEW', 'LAURUSLABS', 'LXCHEM', 'LEMONTREE', 'LICI', 'LINDEINDIA', 'LLOYDSME', 'LUPIN', 'MMTC', 'MRF', 'MTARTECH', 'LODHA', 'MGL', 'MAHSEAMLES', 'M&MFIN', 'M&M', 'MHRIL', 'MAHLIFE', 'MANAPPURAM', 'MRPL', 'MANKIND', 'MARICO', 'MARUTI', 'MASTEK', 'MFSL', 'MAXHEALTH', 'MAZDOCK', 'MEDPLUS', 'METROBRAND',
            'METROPOLIS', 'MINDACORP','CEINSYSTECH','MSUMI', 'MOTILALOFS', 'MPHASIS', 'MCX', 'MUTHOOTFIN', 'NATCOPHARM', 'NBCC', 'NCC', 'NHPC', 'NLCINDIA', 'NMDC', 'NSLNISP', 'NTPC', 'NH', 'NATIONALUM', 'NAVINFLUOR', 'NESTLEIND', 'NETWORK18', 'NAM-INDIA', 'NUVAMA', 'NUVOCO', 'OBEROIRLTY', 'ONGC', 'OIL', 'OLECTRA', 'PAYTM', 'OFSS', 'POLICYBZR', 'PCBL', 'PIIND', 'PNBHOUSING', 'PNCINFRA', 'PVRINOX', 'PAGEIND', 'PATANJALI', 'PERSISTENT', 'PETRONET', 'PHOENIXLTD', 'PIDILITIND',  'PPLPHARMA', 'POLYMED', 'POLYCAB', 'POONAWALLA', 'PFC', 'POWERGRID', 'PRAJIND', 'PRESTIGE', 'PRINCEPIPE', 'PRSMJOHNSN', 'PGHH', 'PNB', 'QUESS', 'RRKABEL', 'RBLBANK', 'RECLTD', 'RHIM', 'RITES', 'RADICO', 'RVNL', 'RAILTEL', 'RAINBOW', 'RAJESHEXPO', 'RKFORGE', 'RCF', 'RATNAMANI', 'RTNINDIA', 'RAYMOND']

stocks2026_new = [
'NIFTY','HDFCBANK','RELIANCE','INFY','ICICIBANK','TCS','KOTAKBANK','ITC','LT','HINDUNILVR','AXISBANK',
'SBIN','BAJFINANCE','BHARTIARTL','ASIANPAINT','HCLTECH','TITAN','TATASTEEL','MARUTI','SUNPHARMA','BAJAJFINSV',
'M&M','TECHM','POWERGRID','WIPRO','HINDALCO','JSWSTEEL','NESTLEIND','GRASIM','INDUSINDBK',
'ADANIPORTS','ONGC','HDFCLIFE','CIPLA','DRREDDY','TATACONSUM','SBILIFE',
'UPL','COALINDIA','BPCL','HEROMOTOCO','BDL','ADANIPOWER','LUPIN','FLUOROCHEM',
'TORNTPOWER','LALPATHLAB','GLAND','MAZDOCK','BHARATFORG','DALBHARAT','IPCALAB','KPITTECH','POLICYBZR','JSWENERGY',
'SYNGENE','JUBLFOOD','ZEEL','LODHA','TIINDIA','LAURUSLABS','NMDC','SUNTV','DEVYANI',
'POLYCAB','UNIONBANK','ABFRL','LTTS','BALKRISIND','APLAPOLLO','IGL','AUBANK','BIOCON',
'TATACOMM','AUROPHARMA','ACC','RVNL','ASHOKLEY','DELHIVERY','BATAINDIA','COROMANDEL','FEDERALBNK','OIL',
'FORTIS','IDFCFIRSTB','BANDHANBNK','LICHSGFIN','HDFCAMC','ESCORTS','INDHOTEL','PRESTIGE','COFORGE',
'MFSL','INDUSTOWER','MSUMI','PFC','CUMMINSIND','PETRONET','MAXHEALTH','DEEPAKNTR',
'NYKAA','FACT','IRFC','RAMCOCEM','CONCOR','GODREJPROP','SAIL','GUJGASLTD','TATACHEM',
'NHPC','INDIANB','OBEROIRLTY','BANKINDIA','RECLTD','ASTRAL','SONACOMS','APOLLOTYRE','MANKIND',
'VOLTAS','UBL','POONAWALLA','LTF','CROMPTON','ABCAPITAL','YESBANK','HINDPETRO','PATANJALI','IDEA',
'MPHASIS','M&MFIN','PAYTM','CGPOWER','DATAPATTNS','AEGISLOG','GRANULES','MRPL','SUZLON','IRB',
'ANGELONE','BSE','REDINGTON','LATENTVIEW','INTELLECT','METROPOLIS','BIKAJI','CYIENT','CREDITACC','GLENMARK'
]


stocks2026 = [
    'SILVERBEES',
    'GOLDBEES',
    'NIFTY 50',
    'ANGELONE',
    'BANKINDIA',
    'TECHM',
    'UNIONBANK',
    'INDUSINDBK',
    'ACE',
    'ACUTAAS',
    'AEROFLEX',
    'AETHER',
    'AGI',
    'ANANTRAJ',
    'ASHOKA',
    'AZAD',
    'BALUFORGE',
    'BEL',
    'BORORENEW',
    'BSE',
    'CDSL',
    'CUPID',
    'DYNAMATECH',
    'EPACK',
    'FEDERALBNK',
    'FEDFINA',
    'GABRIEL',
    'GESHIP',
    'GRAVITA',
    'HINDZINC',
    'HIRECT',
    'IEX',
    'INOXWIND',
    'IIFL',
    'INDIASHLTR',
    'INTERARCH',
    'IONEXCHANG',
    'IREDA',
    'JAMNAAUTO',
    'JKIL',
    'JSFB',
    'JSWENERGY',
    'JSWSTEEL',
    'KAYNES',
    'KIRIINDUS',
    'KPIGREEN',
    'MAXHEALTH',
    'MAZDOCK',
    'MOTILALOFS',
    'NYKAA',
    'PENIND',
    'PGIL',
    'PGEL',
    'POONAWALLA',
    'PREMIERENE',
    'PRIVISCL',
    'QPOWER',
    'SAMHI',
    'SANSERA',
    'SENCO',
    'SHAKTIPUMP',
    'SHAILY',
    'SHRIRAMFIN',
    'SKYGOLD',
    'SPICEJET',
    'STYLAMIND',
    'SUPRIYA',
    'SYRMA',
    'TARIL',
    'TATACAP',
    'TDPOWERSYS',
    'TECHNOE',
    'TIMETECHNO',
    'TRANSRAILL',
    'UJJIVANSFB',
    'UPL',
    'WABAG',
    'WEBELSOLAR',
    'YATHARTH',
    'ZAGGLE'
]
